# Generated by Django 4.1.5 on 2023-01-06 20:06

import django.core.validators
from django.db import migrations, models
import sol_lib.custom_models.char_models
import sol_lib.custom_models.timestamps

class Migration(migrations.Migration):

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ActionCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', sol_lib.custom_models.char_models.LowerCaseCharField(max_length=32)),
            ],
        ),
        migrations.CreateModel(
            name='Action',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', sol_lib.custom_models.timestamps.ISO8601_Timestamp(max_length=32)),
                ('duration', sol_lib.custom_models.timestamps.ISO8601_Duration(max_length=32)),
                ('subject', models.CharField(max_length=255)),
                ('note', models.TextField(blank=True, null=True)),
                ('mood', models.IntegerField(validators=[django.core.validators.MinValueValidator(0),
                                                         django.core.validators.MaxValueValidator(10)])),
                ('category', models.ManyToManyField(to='eva_clockwork_api.actioncategory')),
            ],
        ),
    ]