# Generated by Django 4.1.5 on 2023-01-08 16:48

from django.db import migrations
import sol_lib.custom_models.timestamps


class Migration(migrations.Migration):

    dependencies = [
        ('eva_clockwork_api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='action',
            name='duration',
            field=sol_lib.custom_models.timestamps.ISO8601_Duration(max_length=32, null=True),
        ),
    ]
