# Generated by Django 4.1.5 on 2023-01-08 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eva_clockwork_api', '0002_alter_action_duration'),
    ]

    operations = [
        migrations.AlterField(
            model_name='action',
            name='note',
            field=models.TextField(null=True),
        ),
    ]
