# Generated by Django 4.1.3 on 2022-11-06 16:04

import custom_models.char_models
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='StreamCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('twitch_id', models.PositiveIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='StreamPlatform',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', custom_models.char_models.LowerCaseCharField(max_length=25)),
            ],
        ),
        migrations.CreateModel(
            name='StreamTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', custom_models.char_models.LowerCaseCharField(max_length=25)),
            ],
        ),
        migrations.CreateModel(
            name='StreamLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4)),
                ('name', models.CharField(max_length=255)),
                ('date', models.DateField()),
                ('day_of_streaming', models.PositiveIntegerField()),
                ('duration', models.PositiveIntegerField(blank=True, default=None, null=True)),
                ('youtube_link', models.URLField(blank=True, null=True)),
                ('category', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.RESTRICT, to='api_streaming.streamcategory')),
                ('platform', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='api_streaming.streamplatform')),
                ('tags', models.ManyToManyField(to='api_streaming.streamtag')),
            ],
        ),
    ]
