### Test Eva Clockwork API
### --------------------------------------------------------------------------------------------------------------------
GET http://127.0.0.1:8000/eva/clockwork/api
Content-Type: application/json